# Generated by Django 4.1 on 2022-08-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='img',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='produtos/'),
        ),
    ]
